CREATE TABLE Product
(
    id    int generated by default as identity primary key,
    name  varchar not null,
    price decimal
);

CREATE TABLE Review
(
    id          int generated by default as identity primary key,
    name       varchar not null,
    description varchar not null,
    mark        int     not null,
    product_id int references Product(id)
);

